# Generated by Django 3.1 on 2020-08-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_no', models.IntegerField()),
                ('addr', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_no', models.IntegerField()),
                ('url', models.CharField(max_length=1024)),
                ('desc', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(verbose_name='start display datetime')),
                ('end_date', models.DateTimeField(verbose_name='end display datetime')),
                ('mod_date', models.DateTimeField()),
                ('reg_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RankCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.IntegerField(verbose_name='category number')),
                ('cat_name', models.CharField(max_length=32, verbose_name='category name')),
                ('cat_code', models.CharField(max_length=16, verbose_name='category code')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggmorning.rankcat')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggmorning.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=64)),
                ('prop_value', models.IntegerField()),
                ('hotel_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggmorning.hotel')),
            ],
        ),
    ]
